dist: xenial
sudo: required
language: python
python:
  - "3.8"
cache: pip
services:
- postgresql
before_install:
- pip install -U setuptools
- pip install -U pysam
- pip install -U cython
- pip install -U uta_align
script: make test
